# Test the Async feature in Ansible
 - name: sample command playbook
   hosts: localhost
   connection: local
   gather_facts: false
   tasks:
     - name: sample command2
       ping:
       register: ps_output
       
     - debug:
         msg: "Hi HRU Amey N Smrithi {{ ps_output }}"
